// Stamps a content-derived build id into every cache-bust site so a native
// rebuild never needs manual version bumping:
//   1. public/usd-webview-bindings/usdWebViewBindings.js lines 1-2
//      (_wasmBuildId / _wrapperBuildId)
//   2. src/usd/generated/buildId.ts (imported by UsdWebViewRuntime.ts)
//
// The id is wasm-<first 12 hex of sha256(wasm)> so identical rebuilds are
// no-ops and any binary change is a guaranteed cache bust.
//
// Usage: node tools/native-build/stamp-build.mjs

import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

const REPO_ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..", "..");
const WASM_PATH = path.join(REPO_ROOT, "public", "usd-webview-bindings", "usdWebViewBindingsModule.wasm");
const WRAPPER_PATH = path.join(REPO_ROOT, "public", "usd-webview-bindings", "usdWebViewBindings.js");
const BUILD_ID_TS_PATH = path.join(REPO_ROOT, "src", "usd", "generated", "buildId.ts");

export async function stampBuild() {
  const wasmBytes = await fs.readFile(WASM_PATH);
  const digest = crypto.createHash("sha256").update(wasmBytes).digest("hex").slice(0, 12);
  const buildId = `wasm-${digest}`;

  const wrapper = await fs.readFile(WRAPPER_PATH, "utf8");
  const lines = wrapper.split("\n");
  if (!lines[0]?.includes("_wasmBuildId") || !lines[1]?.includes("_wrapperBuildId")) {
    throw new Error(
      `${WRAPPER_PATH} does not start with the _wasmBuildId/_wrapperBuildId lines this script expects.`
    );
  }
  lines[0] = `const _wasmBuildId = "${buildId}"; // stamped by tools/native-build/stamp-build.mjs`;
  lines[1] = `const _wrapperBuildId = "${buildId}";`;
  await fs.writeFile(WRAPPER_PATH, lines.join("\n"), "utf8");

  await fs.mkdir(path.dirname(BUILD_ID_TS_PATH), { recursive: true });
  await fs.writeFile(
    BUILD_ID_TS_PATH,
    `// Generated by tools/native-build/stamp-build.mjs — do not edit.\n` +
      `export const WASM_BUILD_NAME = "${buildId}";\n`,
    "utf8"
  );

  return buildId;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const buildId = await stampBuild();
  console.log(`Stamped native build id: ${buildId}`);
}
